#!/usr/bin/env python3
"""Emit golden S(v,t) fixtures so the TypeScript venue scorer can be tested for
parity with the offline engine's recommender score.

Expected values are computed from the SHIPPED frontend artifacts
(public/data/nyc/{venues.json, hex_metrics-*.json, category_curves.json}) using
the engine's scoring formula, reproduced verbatim below from
immersion_data/pipeline/assemble_scores.py (score(), lines 47-60). Because both
sides consume the same compacted inputs, agreement is exact up to float noise —
the test asserts a tight tolerance, catching any drift in the client formula.

The fixture also encodes the engine day-of-week convention (Mon=0), so a test
that indexes category curves by the exporter's `dayOfWeek` field only matches
when the WS9 day-slice fix is correct.

Run:  python3 pipeline/generate_golden_scores.py
Writes: src/lib/venueScores.golden.json
"""
from __future__ import annotations

import json
from pathlib import Path

# --- engine formula, copied verbatim from assemble_scores.py -----------------
LAMBDA = 1.0
GAMMA = 0.6
TIME_FLOOR = 0.25
SCALE = 50.0


def score(q, a, l, t, conf_a, conf_l, conf_t, fc):
    q01, a01, l01, t01 = q / 100.0, a / 100.0, l / 100.0, t / 100.0
    time = TIME_FLOOR + (1 - TIME_FLOOR) * fc
    activity = 1 - conf_a * 0.5 * (1 - a01)
    local = 1 + conf_l * LAMBDA * l01
    tourist = 1 - conf_t * GAMMA * t01
    return SCALE * q01 * time * activity * local * tourist
# -----------------------------------------------------------------------------

# Frontend day key -> engine day-of-week (Mon=0..Sun=6). Mirrors export_frontend.
ENGINE_DOW = {"mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6}
# (day, hour) samples: a weekday evening, a weekend late night, a weekend
# morning, and a Friday near-midnight — spanning bar/nightlife wrap-around bins.
SAMPLES = [("mon", 20), ("sat", 22), ("sun", 9), ("fri", 23)]

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "public" / "data" / "nyc"


def load_day(day: str) -> dict:
    return json.loads((DATA / f"hex_metrics-{day}.json").read_text())


def pick_venues(venues: list[dict], day_records: dict) -> list[dict]:
    """Deterministically pick a spread: first venue seen per category, plus the
    highest- and lowest-quality eligible venues, all with hex metrics present."""
    present = [v for v in venues if v["h3"] in day_records]
    chosen: dict[str, dict] = {}
    for v in present:
        chosen.setdefault(v["category"], v)  # first per category
    eligible = [v for v in present if v["qualityPrior"] >= 0.2]
    if eligible:
        chosen["__max_q"] = max(eligible, key=lambda v: v["qualityPrior"])
        chosen["__min_q"] = min(eligible, key=lambda v: v["qualityPrior"])
    # de-dup by id, keep stable order
    seen, out = set(), []
    for v in chosen.values():
        if v["id"] not in seen:
            seen.add(v["id"])
            out.append(v)
    return out


def main() -> None:
    venues = json.loads((DATA / "venues.json").read_text())
    curves = json.loads((DATA / "category_curves.json").read_text())
    day_cache = {day: load_day(day) for day, _ in SAMPLES}

    sample_venues = pick_venues(venues, day_cache[SAMPLES[0][0]]["records"])

    rows = []
    for v in sample_venues:
        curve = curves.get(v["category"])
        for day, hour in SAMPLES:
            records = day_cache[day]["records"]
            rec = records.get(v["h3"])
            if rec is None:
                continue
            a_arr, l_arr, t_arr, conf = rec
            hb = ENGINE_DOW[day] * 24 + hour
            fc = curve[hb] if curve else 1.0
            expected = score(
                v["qualityPrior"] * 100.0,
                a_arr[hour], l_arr[hour], t_arr[hour],
                conf[0] / 100.0, conf[1] / 100.0, conf[2] / 100.0,
                fc,
            )
            rows.append({
                "venueId": v["id"], "category": v["category"], "h3": v["h3"],
                "day": day, "hour": hour, "expected": round(expected, 6),
            })

    # One neutral (no-hex) case: every context term collapses to 1.0.
    neutral_seed = sample_venues[0]
    neutral_curve = curves.get(neutral_seed["category"]) or [1.0] * 168
    neutral_fc = neutral_curve[ENGINE_DOW["fri"] * 24 + 20]
    neutral = {
        "venueId": neutral_seed["id"], "category": neutral_seed["category"],
        "day": "fri", "hour": 20, "fc": round(neutral_fc, 6),
        "qualityPrior": neutral_seed["qualityPrior"],
        "expected": round(score(neutral_seed["qualityPrior"] * 100.0, 0, 0, 0, 0, 0, 0, neutral_fc), 6),
    }

    out = {
        "note": "Generated by pipeline/generate_golden_scores.py. Expected S(v,t) "
                "from the engine formula on shipped compacted inputs.",
        "rows": rows,
        "neutral": neutral,
    }
    dest = ROOT / "src" / "lib" / "venueScores.golden.json"
    dest.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {dest.relative_to(ROOT)} ({len(rows)} rows + 1 neutral)")


if __name__ == "__main__":
    main()
