import type { PlaceCategory } from "@/lib/types/database";

export const CATEGORY_TAGS: Record<PlaceCategory, string[]> = {
  restaurant: [
    "worth the wait",
    "hidden gem",
    "great for dates",
    "solo-friendly",
    "outdoor seating",
    "late night",
    "budget",
    "splurge",
  ],
  cafe: [
    "worth the wait",
    "hidden gem",
    "great for dates",
    "solo-friendly",
    "outdoor seating",
    "late night",
    "budget",
    "splurge",
  ],
  bar: [
    "worth the wait",
    "hidden gem",
    "great for dates",
    "solo-friendly",
    "outdoor seating",
    "late night",
    "budget",
    "splurge",
  ],
  park: [
    "sunrise spot",
    "sunset spot",
    "off the beaten path",
    "family-friendly",
    "quiet",
  ],
  viewpoint: [
    "sunrise spot",
    "sunset spot",
    "off the beaten path",
    "family-friendly",
    "quiet",
  ],
  shop: ["unique finds", "local goods", "budget", "splurge"],
  experience: ["bucket list", "repeat visit", "seasonal", "free"],
};

export const CATEGORY_MAP: Record<string, PlaceCategory> = {
  restaurant: "restaurant",
  food: "restaurant",
  meal_delivery: "restaurant",
  meal_takeaway: "restaurant",
  bar: "bar",
  night_club: "bar",
  cafe: "cafe",
  bakery: "cafe",
  park: "park",
  campground: "park",
  natural_feature: "park",
  shopping_mall: "shop",
  store: "shop",
  clothing_store: "shop",
  book_store: "shop",
  tourist_attraction: "viewpoint",
  church: "viewpoint",
  museum: "viewpoint",
  art_gallery: "viewpoint",
  point_of_interest: "experience",
  amusement_park: "experience",
  spa: "experience",
  gym: "experience",
  stadium: "experience",
};
